# Build and publish ruff-api for wasm.
#
# Assumed to run as a subworkflow of .github/workflows/release.yml; specifically, as a publish
# job within `cargo-dist`.
name: "Build and publish wasm"

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      plan:
        required: true
        type: string

env:
  CARGO_INCREMENTAL: 0
  CARGO_NET_RETRY: 10
  CARGO_TERM_COLOR: always
  RUSTUP_MAX_RETRIES: 10

jobs:
  ruff_wasm:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - name: "Install Rust toolchain"
        run: rustup target add wasm32-unknown-unknown
      - uses: jetli/wasm-pack-action@v0.4.0
      - uses: jetli/wasm-bindgen-action@v0.2.0
      - name: "Run wasm-pack build"
        run: wasm-pack build --target web --scope astral-sh crates/ruff_wasm
      - run: cd crates/ruff_wasm/pkg

      # Need to use generated pkg directory as working_directory
      # Otherwise, the .npmrc generated by the action gets put in the root and not used since there's no root package.json
      # The generated .npmrc reads from $NODE_AUTH_TOKEN for npm auth
      - uses: actions/setup-node@v4
        working_directory: crates/ruff_wasm/pkg
        with:
          node-version: 18
          registry-url: "https://registry.npmjs.org"
      - name: "Publish"
        working_directory: crates/ruff_wasm/pkg
        run: npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}